### ISSUE TITLE
退款接口错误

### ISSUE THREAD

**Issue by jianandgui** [wxpay/WXPay-SDK-Java#17]
java.io.IOException: toDerInputStream rejects tag type 77
	at sun.security.util.DerValue.toDerInputStream(DerValue.java:847) ~[na:1.8.0_112]
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1915) ~[na:1.8.0_112]

我导入了您的jar包 报这样的错 是我的证书有问题吗

**Comment by jianandgui** [comment]
我的证书 是直接复制的 没有从平台上下 也没有导入 会不会有影响啊
